name: Deploy to Cloudflare Pages

on:
  push:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: jdx/mise-action@v2
        with:
          experimental: true # [default: false] enable experimental features
          install: false
          log_level: debug # [default: info] log level

      - name: Install bun
        run: mise use bun

      - uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0-dev.3091+42e48b83b

      - name: Zig Action Cache
        uses: Hanaasagi/zig-action-cache@v1.1.5
        with:
          cache-directories: ".zig-cache"

      - name: Build
        run: bun run build

      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: simonhartcher-com
          directory: zig-out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
